export const MENU_ITEMS = [
  {
    id: 1,
    text: "Tablero",
    iconLeft: "home",
    iconRight: "chevron_right",
    disabled: false,
    link: "/tablero",
  },
  {
    id: 2,
    text: "Transferir",
    iconLeft: "compare_arrows",
    iconRight: "chevron_right",
    disabled: false,
    link: "/transfers",
  },
  {
    id: 3,
    text: "Pagar",
    iconLeft: "money",
    iconRight: "chevron_right",
    disabled: false,
    link: "/configuracion",
  },
  {
    id: 4,
    text: "Mis transacciones",
    iconLeft: "person",
    iconRight: "chevron_right",
    disabled: false,
    link: "/transfers-history",
  },
  {
    id: 5,
    text: "Gestionar",
    iconLeft: "rotate_right",
    iconRight: "chevron_right",
    disabled: false,
    link: "/mensajes",
  },
  {
    id: 6,
    text: "Cheques",
    iconLeft: "fact_check",
    iconRight: "chevron_right",
    disabled: false,
    link: "/favoritos",
  },
  {
    id: 7,
    text: "Paganet",
    iconLeft: "paid",
    iconRight: "chevron_right",
    disabled: false,
    link: "/historial",
  },
  {
    id: 8,
    text: "Administrar",
    iconLeft: "person",
    iconRight: "chevron_right",
    disabled: false,
    link: "/ayuda",
  },
  {
    id: 10,
    text: "Configuración",
    iconLeft: "settings",
    iconRight: "chevron_right",
    disabled: false,
    link: "/logout",
  },
];
